### ISSUE TITLE
Update to NatMic 1.3.1

### ISSUE THREAD

**Issue by AttackingHobo** [olokobayusuf/NatMicCorder-Demo#2]
> Assets/Scripts/NatMicCorder.cs(45,29): error CS0117: `NatMic.AudioDevice' does not contain a definition for `Devices'

I think I might have fixed it by changing:
`audioDevice = AudioDevice.Devices[0];`

to:
`audioDevice = AudioDevice.GetDevices()[0];`

You might want to verify that this is the right way of doing it.

**Comment by olokobayusuf** [comment]
Yup your change is correct.

**Comment by olokobayusuf** [comment]
a471ec062ca8613f2cf6aea558b56423993eb4b1
